### **Generation of Bootstrap Samples**

In [16]:
import random

In [17]:
data = [1, 2, 3, 4, 5]

In [18]:
# sample 5 data points for 10 times
for i in range(100):
  sample = random.choices(data, k = 5)
  print(f"Sample {i+1}: {sample}")

Sample 1: [2, 3, 1, 4, 5]
Sample 2: [3, 3, 4, 4, 1]
Sample 3: [5, 5, 5, 3, 3]
Sample 4: [4, 3, 5, 4, 2]
Sample 5: [1, 3, 5, 5, 5]
Sample 6: [1, 3, 3, 1, 4]
Sample 7: [1, 5, 5, 3, 2]
Sample 8: [4, 1, 2, 2, 4]
Sample 9: [2, 5, 5, 3, 1]
Sample 10: [1, 4, 4, 1, 3]
Sample 11: [1, 3, 3, 1, 1]
Sample 12: [3, 1, 5, 3, 4]
Sample 13: [3, 1, 5, 3, 2]
Sample 14: [1, 5, 5, 1, 5]
Sample 15: [2, 1, 3, 2, 4]
Sample 16: [3, 3, 2, 4, 1]
Sample 17: [2, 2, 2, 2, 5]
Sample 18: [4, 2, 3, 3, 4]
Sample 19: [5, 5, 3, 1, 5]
Sample 20: [1, 2, 2, 5, 5]
Sample 21: [5, 5, 5, 2, 2]
Sample 22: [1, 5, 5, 1, 4]
Sample 23: [1, 4, 4, 4, 1]
Sample 24: [2, 4, 4, 5, 3]
Sample 25: [3, 2, 1, 2, 2]
Sample 26: [5, 2, 5, 5, 4]
Sample 27: [4, 3, 1, 2, 4]
Sample 28: [4, 5, 3, 3, 1]
Sample 29: [2, 4, 2, 4, 4]
Sample 30: [2, 5, 3, 5, 3]
Sample 31: [5, 5, 2, 3, 5]
Sample 32: [3, 3, 3, 3, 5]
Sample 33: [2, 3, 5, 4, 1]
Sample 34: [3, 2, 3, 5, 4]
Sample 35: [2, 4, 1, 3, 1]
Sample 36: [5, 3, 4, 2, 3]
Sample 37: [3, 5, 2, 1, 3]
Sample 38:

### **Bootstrap Manual**

In [19]:
import numpy as np

In [20]:
# Sample data
data = np.array([1, 2, 3, 4, 5])

In [21]:
# num_samples
bootstrap_samples = [np.random.choice(data, size = len(data), replace = True) for _ in range(100)]

In [22]:
len(bootstrap_samples)

100

In [23]:
bootstrap_samples

[array([2, 1, 2, 5, 5]),
 array([5, 2, 2, 4, 5]),
 array([2, 3, 4, 5, 1]),
 array([5, 1, 4, 5, 3]),
 array([3, 1, 4, 3, 2]),
 array([1, 4, 5, 1, 4]),
 array([3, 2, 1, 3, 1]),
 array([3, 1, 4, 5, 1]),
 array([2, 4, 2, 3, 5]),
 array([2, 5, 1, 2, 4]),
 array([1, 5, 3, 5, 5]),
 array([2, 4, 2, 4, 2]),
 array([1, 1, 1, 5, 4]),
 array([1, 1, 4, 2, 4]),
 array([4, 5, 3, 3, 4]),
 array([1, 4, 5, 4, 4]),
 array([4, 4, 3, 4, 3]),
 array([3, 4, 4, 3, 4]),
 array([2, 3, 3, 5, 2]),
 array([4, 2, 4, 1, 5]),
 array([3, 1, 4, 4, 2]),
 array([5, 5, 3, 4, 3]),
 array([2, 4, 1, 1, 2]),
 array([4, 3, 1, 3, 2]),
 array([2, 1, 4, 3, 1]),
 array([2, 2, 4, 5, 4]),
 array([4, 2, 1, 4, 5]),
 array([3, 2, 4, 3, 4]),
 array([5, 3, 5, 3, 4]),
 array([1, 2, 3, 3, 1]),
 array([4, 4, 5, 2, 1]),
 array([5, 4, 2, 2, 1]),
 array([1, 4, 3, 4, 3]),
 array([5, 1, 1, 3, 1]),
 array([3, 5, 3, 5, 1]),
 array([1, 4, 1, 3, 4]),
 array([2, 4, 2, 5, 4]),
 array([4, 2, 1, 1, 3]),
 array([2, 2, 3, 5, 5]),
 array([2, 1, 4, 5, 4]),


In [24]:
# Calcuate the mean of samples
bootstrap_mean = [np.mean(sample) for sample in bootstrap_samples]

In [25]:
bootstrap_mean[:10]

[3.0, 3.6, 3.0, 3.6, 2.6, 3.0, 2.0, 2.8, 3.2, 2.8]

### **Libraries**

**Configuration**

In [26]:
import warnings
warnings.filterwarnings("ignore")

**Classical Libraries**

In [27]:
import numpy as np
import pandas as pd

**Machine Learning Libraries**

In [28]:
from sklearn.metrics import *
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score

#**Mounting Google Drive**

In [29]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [30]:
df = pd.read_csv("/content/drive/MyDrive/diabetes.csv")

In [31]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

#### **Feature Division and Split**

In [32]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [33]:
# Features
X = df.drop("Outcome", axis = 1)

# Target
y = df["Outcome"]

In [34]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 23)

### **Manual Model**

In [35]:
scores1 = cross_val_score(DecisionTreeClassifier(), X, y, cv = 5)

In [36]:
scores1

array([0.68181818, 0.66883117, 0.69480519, 0.77777778, 0.7254902 ])

In [37]:
scores1.mean()

0.7097445038621509

#### **Bagging Classifier**

In [38]:
model = BaggingClassifier(
    estimator = DecisionTreeClassifier(), # Base learing model
    n_estimators = 5)

In [39]:
scores2 = cross_val_score(model, X, y, cv = 5)

In [40]:
scores2

array([0.71428571, 0.67532468, 0.70779221, 0.79084967, 0.73856209])

In [41]:
scores2.mean()

0.725362872421696

#### **Implement on Multiple Models**

In [42]:
models = {
    "Decision Tree" : BaggingClassifier(n_estimators = 100, random_state = 42),
    "Logistic Regression" : BaggingClassifier(LogisticRegression(), n_estimators = 100, random_state = 42),
    "Random Forest" : RandomForestClassifier(n_estimators = 100, random_state = 42)
}

In [43]:
for name, model in models.items():
  print(f"Name of the model: {name}")
  model.fit(x_train, y_train)

  pred = model.predict(x_test)

  print(f"Accuracy: {accuracy_score(y_test, pred)}")
  print("================================")
  print(classification_report(y_test, pred))

Name of the model: Decision Tree
Accuracy: 0.7662337662337663
              precision    recall  f1-score   support

           0       0.81      0.84      0.82       148
           1       0.69      0.64      0.66        83

    accuracy                           0.77       231
   macro avg       0.75      0.74      0.74       231
weighted avg       0.76      0.77      0.76       231

Name of the model: Logistic Regression
Accuracy: 0.7705627705627706
              precision    recall  f1-score   support

           0       0.79      0.88      0.83       148
           1       0.73      0.58      0.64        83

    accuracy                           0.77       231
   macro avg       0.76      0.73      0.74       231
weighted avg       0.77      0.77      0.76       231

Name of the model: Random Forest
Accuracy: 0.7532467532467533
              precision    recall  f1-score   support

           0       0.80      0.82      0.81       148
           1       0.67      0.63      0.65  